apiVersion: v1
kind: Pod
metadata:
  name: go-demo-2
  labels:
    type: stack
spec:
  containers:
  - name: db
    image: mongo:3.6
  - name: api-1
    image: public.ecr.aws/b9a2w3x7/go-demo-2
    env:
    - name: DB
      value: localhost
  - name: api-2
    image: public.ecr.aws/b9a2w3x7/go-demo-2
    env:
    - name: DB
      value: localhost
